import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { prisma } from '@/lib/db/client';

// GET /api/export/pdf - Generate HTML report of completed conversations
export async function GET(request: NextRequest) {
  try {
    const session = await auth();

    if (!session) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    const { searchParams } = new URL(request.url);
    const scenarioId = searchParams.get('scenarioId');

    // Get user info
    const user = await prisma.user.findUnique({
      where: { id: session.user.id },
      select: { username: true },
    });

    // Get all completed conversations with summaries
    const conversations = await prisma.conversation.findMany({
      where: {
        userId: session.user.id,
        status: 'completed',
        ...(scenarioId && { scenarioId }),
      },
      include: {
        persona: {
          select: {
            name: true,
            description: true,
            roleType: true,
          },
        },
        scenario: {
          select: {
            title: true,
          },
        },
        summary: true,
      },
      orderBy: {
        completedAt: 'desc',
      },
    });

    const html = generateHTMLReport(user?.username || 'User', conversations);

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `inline; filename="persuaider-report-${new Date().toISOString().split('T')[0]}.html"`,
      },
    });
  } catch (error) {
    console.error('Error generating report:', error);
    return NextResponse.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    );
  }
}

function generateHTMLReport(username: string, conversations: any[]): string {
  const date = new Date().toLocaleDateString();

  let conversationsHTML = '';

  if (conversations.length === 0) {
    conversationsHTML = '<p>No completed conversations yet.</p>';
  } else {
    conversationsHTML = conversations.map(conv => {
      const winningArgs = conv.summary?.winningArguments
        ? JSON.parse(conv.summary.winningArguments)
        : [];

      return `
        <div style="margin-bottom: 30px; border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px;">
          <h3 style="color: #4f46e5; margin-bottom: 5px;">${conv.persona.name}</h3>
          <p style="color: #9ca3af; font-size: 12px; margin-bottom: 10px;">Scenario: ${conv.scenario?.title || 'N/A'}</p>
          <p style="color: #6b7280; margin-bottom: 15px;">${conv.persona.description}</p>

          ${conv.summary?.overallScore != null ? `
            <p style="font-size: 18px; font-weight: bold; color: #4f46e5;">Score: ${conv.summary.overallScore}/100</p>
          ` : ''}

          ${winningArgs.length > 0 ? `
            <h4 style="margin-top: 20px; margin-bottom: 10px;">Key Arguments:</h4>
            <ul style="list-style: none; padding: 0;">
              ${winningArgs.map((arg: any) => `
                <li style="margin-bottom: 10px; padding-left: 15px; border-left: 3px solid #4f46e5;">
                  <p style="margin-top: 5px;">${arg.text || JSON.stringify(arg)}</p>
                </li>
              `).join('')}
            </ul>
          ` : ''}
        </div>
      `;
    }).join('');
  }

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Persuaider - Report</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
          background: #f9fafb;
        }
        .header {
          background: white;
          padding: 30px;
          border-radius: 8px;
          margin-bottom: 30px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        .header h1 {
          color: #1f2937;
          margin: 0 0 10px 0;
        }
        .header p {
          color: #6b7280;
          margin: 0;
        }
        @media print {
          body { background: white; }
          .header { box-shadow: none; border: 1px solid #e5e7eb; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Persuaider - Training Report</h1>
        <p><strong>Participant:</strong> ${username}</p>
        <p><strong>Date:</strong> ${date}</p>
        <p><strong>Completed Conversations:</strong> ${conversations.length}</p>
      </div>

      ${conversationsHTML}

      <div style="margin-top: 40px; padding: 20px; background: #f3f4f6; border-radius: 8px; text-align: center;">
        <p style="margin: 0; color: #6b7280; font-size: 14px;">
          Generated by Persuaider
        </p>
      </div>
    </body>
    </html>
  `;
}
